from facerec_rtree import encode, KNNSequentialIndex, KNNSequential, KNNRtree
import datetime

query = encode('./data/saved/adam-sandler-test.jpeg')
(known, names) = KNNSequentialIndex()

N = 100
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 200
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 400
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 800
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 1600
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 3200
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 6400
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
N = 12000
print(N)
# start = datetime.datetime.now()
# print(KNNRtree(8, query, N))
# print(datetime.datetime.now() - start)
start = datetime.datetime.now()
print(KNNSequential(known, names, query, 8, N))
print(datetime.datetime.now() - start)
